using UnityEngine;
using UnityEngine.Tilemaps;
using System.Collections.Generic;

namespace FarmGame.Farm
{
    /// <summary>
    /// 农田工具预览组件
    /// 负责显示锄头/水壶的预览效果
    /// 
    /// 特性：
    /// - 自生能力：Awake 时自动创建缺失的 GhostTilemap 和 CursorRenderer
    /// - 1+8 预览：锄头显示中心块 + 周围 8 格边界变化
    /// - 颜色反馈：绿色=可用，红色=不可用，蓝色=浇水
    /// </summary>
    public class FarmToolPreview : MonoBehaviour
    {
        #region 单例（Lazy Singleton）
        
        private static FarmToolPreview _instance;
        
        /// <summary>
        /// 单例访问器（Lazy Singleton）
        /// 如果场景中没有 FarmToolPreview，会自动创建一个
        /// </summary>
        public static FarmToolPreview Instance
        {
            get
            {
                if (_instance == null)
                {
                    // 先尝试在场景中查找
                    _instance = FindFirstObjectByType<FarmToolPreview>();
                    
                    if (_instance == null)
                    {
                        // 🔥 真正的自生能力：如果场景没有，直接创建一个
                        var go = new GameObject("FarmToolPreview_AutoGenerated");
                        _instance = go.AddComponent<FarmToolPreview>();
                        Debug.Log("[FarmToolPreview] 自动创建实例（场景中未找到）");
                    }
                }
                return _instance;
            }
        }
        
        #endregion
        
        #region 预览状态枚举
        
        public enum FarmPreviewState
        {
            Hidden,     // 隐藏
            Valid,      // 有效（绿色）
            Invalid     // 无效（红色）
        }
        
        // 🔥 9.0.5 新增：浇水失败原因
        public enum WateringFailureReason
        {
            None,           // 无失败
            NoFarmland,     // 没有耕地数据
            NotTilled,      // 未耕作
            AlreadyWatered, // 已浇水
            HasObstacle,    // 有障碍物
            ManagerNull     // FarmTileManager 为 null
        }
        
        #endregion
        
        #region 配置
        
        [Header("光标配置")]
        [Tooltip("光标 Sprite（方形框）")]
        [SerializeField] private Sprite cursorSprite;
        
        [Tooltip("有效时的颜色（绿色）")]
        [SerializeField] private Color validColor = new Color(0f, 1f, 0f, 0.5f);
        
        [Tooltip("无效时的颜色（红色）")]
        [SerializeField] private Color invalidColor = new Color(1f, 0f, 0f, 0.5f);
        
        [Tooltip("浇水时的颜色（蓝色）")]
        [SerializeField] private Color wateringColor = new Color(0f, 0.5f, 1f, 0.5f);
        
        [Header("预览透明度")]
        [SerializeField, Range(0.1f, 1f)] private float previewAlpha = 0.5f;
        
        [Header("Debug")]
        [SerializeField] private bool showDebugInfo = false;
        
        #endregion
        
        #region 运行时引用（自动创建）
        
        private Tilemap ghostTilemap;
        private TilemapRenderer ghostTilemapRenderer;
        private SpriteRenderer cursorRenderer;
        
        #endregion
        
        #region 状态
        
        private FarmPreviewState currentState = FarmPreviewState.Hidden;
        private Vector3Int lastCellPosition;
        private int lastLayerIndex = -1;
        private bool isHoeMode = false; // true=锄头, false=水壶
        private bool isSeedMode = false; // 🔥 新增：种子模式
        
        // 🔥 新增：当前 Sorting Layer 缓存
        private string currentSortingLayer = "Layer 1";
        
        // 🔥 9.0.4 新增：公开属性供 GameInputManager 查询
        /// <summary>
        /// 当前目标是否在使用距离内
        /// </summary>
        public bool IsInRange { get; private set; }
        
        /// <summary>
        /// 当前光标位置（格子中心世界坐标）
        /// </summary>
        public Vector3 CurrentCursorPos { get; private set; }
        
        /// <summary>
        /// 当前目标的格子坐标
        /// </summary>
        public Vector3Int CurrentCellPos { get; private set; }
        
        /// <summary>
        /// 当前目标的楼层索引
        /// </summary>
        public int CurrentLayerIndex { get; private set; }
        
        // 🔥 新增：种子颜色
        [Header("种子预览配置")]
        [SerializeField] private Color seedValidColor = new Color(0f, 0.8f, 0.2f, 0.6f);
        [SerializeField] private Color seedInvalidColor = new Color(1f, 0.2f, 0f, 0.6f);
        
        // 缓存当前预览的 Tiles（用于清除）
        private HashSet<Vector3Int> currentPreviewPositions = new HashSet<Vector3Int>();
        
        // 🔥 诊断日志去重标志
        private bool _hasLoggedDiagnostics = false;
        private bool _hasLoggedPreviewTiles = false;
        
        // === 🔥 9.0.5 新增：锁定机制 ===
        private bool _isLocked = false;
        private Vector3 _lockedWorldPosition;
        private Vector3Int _lockedCellPos;
        private int _lockedLayerIndex;
        
        // 🔥 9.0.5 新增：浇水失败原因
        public WateringFailureReason LastWateringFailure { get; private set; } = WateringFailureReason.None;
        
        #endregion
        
        #region 生命周期
        
        private void Awake()
        {
            if (_instance == null)
            {
                _instance = this;
                EnsureComponents();
            }
            else if (_instance != this)
            {
                Destroy(gameObject);
            }
        }
        
        private void OnDestroy()
        {
            if (_instance == this)
            {
                _instance = null;
            }
        }
        
        /// <summary>
        /// 自生能力：确保所有必要组件存在
        /// </summary>
        private void EnsureComponents()
        {
            // 🔥 首先确保有 Grid 组件（Tilemap 必须在 Grid 下才能正确显示）
            var grid = GetComponent<Grid>();
            if (grid == null)
            {
                grid = gameObject.AddComponent<Grid>();
                grid.cellSize = new Vector3(1f, 1f, 0f); // 标准 1x1 格子
                grid.cellGap = Vector3.zero;
                grid.cellLayout = GridLayout.CellLayout.Rectangle;
                grid.cellSwizzle = GridLayout.CellSwizzle.XYZ;
            }
            
            // 1. 确保 GhostTilemap 存在
            if (ghostTilemap == null)
            {
                var ghostGO = transform.Find("GhostTilemap");
                if (ghostGO == null)
                {
                    ghostGO = new GameObject("GhostTilemap").transform;
                    ghostGO.SetParent(transform);
                    ghostGO.localPosition = Vector3.zero;
                }
                
                ghostTilemap = ghostGO.GetComponent<Tilemap>();
                if (ghostTilemap == null)
                {
                    ghostTilemap = ghostGO.gameObject.AddComponent<Tilemap>();
                }
                
                ghostTilemapRenderer = ghostGO.GetComponent<TilemapRenderer>();
                if (ghostTilemapRenderer == null)
                {
                    ghostTilemapRenderer = ghostGO.gameObject.AddComponent<TilemapRenderer>();
                }
                
                // 设置 Sorting Layer（使用项目中存在的 Layer 1，高 sortingOrder 确保在地面之上）
                ghostTilemapRenderer.sortingLayerName = "Layer 1";
                ghostTilemapRenderer.sortingOrder = 9999; // 极高值确保在所有地面 Tile 之上
                
                // 设置透明度
                ghostTilemap.color = new Color(1f, 1f, 1f, previewAlpha);
                
                if (showDebugInfo)
                    Debug.Log("[FarmToolPreview] 自动创建 GhostTilemap（含 Grid）");
            }
            
            // 2. 确保 CursorRenderer 存在
            if (cursorRenderer == null)
            {
                var cursorGO = transform.Find("CursorRenderer");
                if (cursorGO == null)
                {
                    cursorGO = new GameObject("CursorRenderer").transform;
                    cursorGO.SetParent(transform);
                    cursorGO.localPosition = Vector3.zero;
                }
                
                cursorRenderer = cursorGO.GetComponent<SpriteRenderer>();
                if (cursorRenderer == null)
                {
                    cursorRenderer = cursorGO.gameObject.AddComponent<SpriteRenderer>();
                }
                
                // 设置 Sorting Layer（使用项目中存在的 Layer 1，高 sortingOrder 确保在预览 Tilemap 之上）
                cursorRenderer.sortingLayerName = "Layer 1";
                cursorRenderer.sortingOrder = 10000; // 比 ghostTilemap 更高
                
                // 设置 Sprite（如果没有配置，程序化生成一个白色方框）
                if (cursorSprite != null)
                {
                    cursorRenderer.sprite = cursorSprite;
                }
                else
                {
                    // 🔥 程序化生成光标 Sprite（1x1 白色 Texture）
                    cursorRenderer.sprite = CreateProceduralCursorSprite();
                    if (showDebugInfo)
                        Debug.Log("[FarmToolPreview] 程序化生成光标 Sprite（未配置 cursorSprite）");
                }
                
                if (showDebugInfo)
                    Debug.Log("[FarmToolPreview] 自动创建 CursorRenderer");
            }
        }
        
        #endregion
        
        #region 公开接口
        
        // === 🔥 9.0.5 新增：锁定机制公开接口 ===
        
        /// <summary>
        /// 是否处于锁定状态
        /// </summary>
        public bool IsLocked => _isLocked;
        
        /// <summary>
        /// 锁定时的世界坐标（供导航回调中距离校验使用）
        /// </summary>
        public Vector3 LockedWorldPos => _lockedWorldPosition;
        
        /// <summary>
        /// 锁定时的格子坐标（供导航中同位置检测使用）
        /// </summary>
        public Vector3Int LockedCellPos => _lockedCellPos;
        
        /// <summary>
        /// 锁定预览位置（点击后调用）
        /// 冻结视觉显示，但实时数据继续更新
        /// </summary>
        public void LockPosition(Vector3 worldPos, Vector3Int cellPos, int layerIndex)
        {
            _isLocked = true;
            _lockedWorldPosition = worldPos;
            _lockedCellPos = cellPos;
            _lockedLayerIndex = layerIndex;
            
            // 🔥 10.1.1补丁002 P3 修复：锁定时执行一次完整的 GhostTilemap 渲染（仅锄头模式）
            if (isHoeMode && FarmlandBorderManager.Instance != null)
            {
                ClearGhostTilemap();
                
                // 检查该位置是否可以锄地
                bool canTill = FarmTileManager.Instance != null &&
                               FarmTileManager.Instance.CanTillAt(layerIndex, cellPos);
                
                // 也检查枯萎作物清除（与 UpdateHoePreview 逻辑一致）
                bool canClearWithered = false;
                if (!canTill && FarmTileManager.Instance != null)
                {
                    var tileData = FarmTileManager.Instance.GetTileData(layerIndex, cellPos);
                    if (tileData?.cropController != null &&
                        tileData.cropController.GetState() == CropState.WitheredImmature)
                        canClearWithered = true;
                }
                
                if (canTill)
                {
                    var previewTiles = FarmlandBorderManager.Instance.GetPreviewTiles(layerIndex, cellPos);
                    foreach (var kvp in previewTiles)
                    {
                        if (kvp.Value != null)
                        {
                            ghostTilemap.SetTile(kvp.Key, kvp.Value);
                            currentPreviewPositions.Add(kvp.Key);
                        }
                    }
                }
            }
            
            // 🔥 10.1.0 AC-1.4：锁定时自动刷新视觉到锁定位置（消除同帧解锁+重锁的视觉跳变）
            UpdateCursor(layerIndex, cellPos);
            
            if (showDebugInfo)
                Debug.Log($"[FarmToolPreview] LockPosition: pos={worldPos}, cell={cellPos}, layer={layerIndex}");
        }
        
        /// <summary>
        /// 解锁预览位置（执行完成/取消后调用）
        /// 恢复视觉跟随鼠标
        /// </summary>
        public void UnlockPosition()
        {
            _isLocked = false;
            
            if (showDebugInfo)
                Debug.Log("[FarmToolPreview] UnlockPosition");
        }
        
        /// <summary>
        /// 🔥 重构：更新锄头预览
        /// 新增参数：playerTransform 和 reach 用于距离检测
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        /// <param name="layerIndex">楼层索引</param>
        /// <param name="cellPos">格子坐标</param>
        /// <param name="playerTransform">玩家 Transform（用于距离检测和 Layer 同步）</param>
        /// <param name="reach">工具使用距离</param>
        public void UpdateHoePreview(int layerIndex, Vector3Int cellPos, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = true;
            isSeedMode = false;
            
            // 🔥 一次性诊断日志（只在首次调用时输出）
            LogDiagnosticsOnce();
            
            // 🔥 Step 1: 更新 Sorting Layer（跟随玩家楼层）
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取格子中心世界坐标
            Vector3 cellCenter = GetCellCenterWorld(layerIndex, cellPos);
            
            // 🔥 Step 2: 障碍物检测（使用 HasFarmingObstacle，不检测 Player）
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(cellCenter);
            
            // 🔥 Step 3: 检查是否可以锄地
            bool canTill = FarmTileManager.Instance != null && 
                           FarmTileManager.Instance.CanTillAt(layerIndex, cellPos);
            
            // 🔥 10.X 纠正：通过 FarmTileData.cropController 查找枯萎作物（替代 CropManager.GetCrop）
            bool canClearWithered = false;
            if (!canTill && FarmTileManager.Instance != null)
            {
                var tileData = FarmTileManager.Instance.GetTileData(layerIndex, cellPos);
                if (tileData?.cropController != null && tileData.cropController.GetState() == CropState.WitheredImmature)
                    canClearWithered = true;
            }
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && (canTill || canClearWithered);
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, cellCenter, playerTransform, reach);
            
            // 🔥 9.0.5：锁定状态下不更新视觉
            if (_isLocked) return;
            
            // 清除旧预览
            ClearGhostTilemap();
            
            // 如果可以锄地，显示 1+8 预览
            if (canTill && FarmlandBorderManager.Instance != null)
            {
                var previewTiles = FarmlandBorderManager.Instance.GetPreviewTiles(layerIndex, cellPos);
                
                // 🔥 诊断：检查 previewTiles 是否为空（一次性输出，不依赖 showDebugInfo）
                if (!_hasLoggedPreviewTiles)
                {
                    _hasLoggedPreviewTiles = true;
                    Debug.Log($"[FarmToolPreview] GetPreviewTiles 返回 {previewTiles.Count} 个 Tile");
                    foreach (var kvp in previewTiles)
                    {
                        Debug.Log($"  - {kvp.Key}: {(kvp.Value != null ? kvp.Value.name : "null")}");
                    }
                }
                
                foreach (var kvp in previewTiles)
                {
                    if (kvp.Value != null)
                    {
                        ghostTilemap.SetTile(kvp.Key, kvp.Value);
                        currentPreviewPositions.Add(kvp.Key);
                    }
                }
            }
            else if (!_hasLoggedPreviewTiles)
            {
                _hasLoggedPreviewTiles = true;
                Debug.Log($"[FarmToolPreview] 跳过 1+8 预览: canTill={canTill}, BorderManager={(FarmlandBorderManager.Instance != null ? "存在" : "null")}");
            }
            
            // 更新光标
            UpdateCursor(layerIndex, cellPos);
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 显示
            Show();
        }
        
        /// <summary>
        /// 🔥 重构：更新水壶预览
        /// 新增参数：playerTransform 和 reach 用于距离检测
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        public void UpdateWateringPreview(int layerIndex, Vector3Int cellPos, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = false;
            isSeedMode = false;
            
            // 🔥 Step 1: 更新 Sorting Layer
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取格子中心世界坐标
            Vector3 cellCenter = GetCellCenterWorld(layerIndex, cellPos);
            
            // 🔥 Step 2: 障碍物检测
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(cellCenter);
            
            // 🔥 Step 3: 检查是否可以浇水
            var tileData = FarmTileManager.Instance?.GetTileData(layerIndex, cellPos);
            bool canWater = tileData != null && 
                            tileData.isTilled && 
                            !tileData.wateredToday;
            
            // 🔥 9.0.5：记录浇水失败原因
            if (hasObstacle)
                LastWateringFailure = WateringFailureReason.HasObstacle;
            else if (FarmTileManager.Instance == null)
                LastWateringFailure = WateringFailureReason.ManagerNull;
            else if (tileData == null)
                LastWateringFailure = WateringFailureReason.NoFarmland;
            else if (!tileData.isTilled)
                LastWateringFailure = WateringFailureReason.NotTilled;
            else if (tileData.wateredToday)
                LastWateringFailure = WateringFailureReason.AlreadyWatered;
            else
                LastWateringFailure = WateringFailureReason.None;
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && canWater;
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, cellCenter, playerTransform, reach);
            
            // 🔥 9.0.5：锁定状态下不更新视觉
            if (_isLocked) return;
            
            // 清除旧预览（水壶不显示 1+8）
            ClearGhostTilemap();
            
            // 更新光标
            UpdateCursor(layerIndex, cellPos);
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 显示
            Show();
        }
        
        /// <summary>
        /// 🔥 新增：更新种子预览
        /// 只显示红/绿光标，隐藏 GhostTilemap
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        /// <param name="alignedPos">对齐后的世界坐标（格子中心）</param>
        /// <param name="seedData">种子数据</param>
        /// <param name="playerTransform">玩家 Transform</param>
        /// <param name="reach">种植距离</param>
        public void UpdateSeedPreview(Vector3 alignedPos, FarmGame.Data.SeedData seedData, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = false;
            isSeedMode = true;
            
            // 🔥 Step 1: 更新 Sorting Layer
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取楼层和格子坐标
            var farmTileManager = FarmTileManager.Instance;
            if (farmTileManager == null)
            {
                currentState = FarmPreviewState.Invalid;
                IsInRange = false;
                UpdateCursorForSeed(alignedPos, false);
                Show();
                return;
            }
            
            int layerIndex = farmTileManager.GetCurrentLayerIndex(alignedPos);
            var tilemaps = farmTileManager.GetLayerTilemaps(layerIndex);
            
            if (tilemaps == null)
            {
                currentState = FarmPreviewState.Invalid;
                IsInRange = false;
                UpdateCursorForSeed(alignedPos, false);
                Show();
                return;
            }
            
            Vector3Int cellPos = tilemaps.WorldToCell(alignedPos);
            
            // 🔥 Step 2: 障碍物检测
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(alignedPos);
            
            // 🔥 Step 3: 检查是否可以种植
            var tileData = farmTileManager.GetTileData(layerIndex, cellPos);
            bool canPlant = tileData != null && tileData.CanPlant();
            
            // 🔥 Step 5: 检查季节（可选）
            bool correctSeason = true;
            if (seedData != null && TimeManager.Instance != null)
            {
                if (seedData.season != FarmGame.Data.Season.AllSeason)
                {
                    var currentSeason = TimeManager.Instance.GetSeason();
                    correctSeason = (int)seedData.season == (int)currentSeason;
                }
            }
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && canPlant && correctSeason;
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, alignedPos, playerTransform, reach);
            
            // 🔥 9.0.5：锁定状态下不更新视觉
            if (_isLocked) return;
            
            // 🔥 种子模式：隐藏 GhostTilemap，只显示光标
            ClearGhostTilemap();
            if (ghostTilemap != null)
            {
                ghostTilemap.gameObject.SetActive(false);
            }
            
            // 更新光标（使用种子颜色）
            UpdateCursorForSeed(alignedPos, isValid);
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 显示光标
            if (cursorRenderer != null)
            {
                cursorRenderer.gameObject.SetActive(true);
            }
        }
        
        /// <summary>
        /// 显示预览
        /// </summary>
        public void Show()
        {
            if (!isSeedMode && ghostTilemap != null)
                ghostTilemap.gameObject.SetActive(true);
            if (cursorRenderer != null)
                cursorRenderer.gameObject.SetActive(true);
        }
        
        /// <summary>
        /// 隐藏预览
        /// </summary>
        public void Hide()
        {
            currentState = FarmPreviewState.Hidden;
            isSeedMode = false;
            
            ClearGhostTilemap();
            
            if (ghostTilemap != null)
                ghostTilemap.gameObject.SetActive(false);
            if (cursorRenderer != null)
                cursorRenderer.gameObject.SetActive(false);
        }
        
        /// <summary>
        /// 检查当前预览是否有效
        /// </summary>
        public bool IsValid()
        {
            return currentState == FarmPreviewState.Valid;
        }
        
        /// <summary>
        /// 获取当前预览状态
        /// </summary>
        public FarmPreviewState GetState()
        {
            return currentState;
        }
        
        #endregion
        
        #region 内部方法
        
        /// <summary>
        /// 🔥 9.0.5 新增：轻量级实时数据更新（不触碰视觉渲染）
        /// 锁定状态下也会被调用，确保 GameInputManager 能读到最新的鼠标位置数据
        /// </summary>
        private void UpdateRealtimeData(int layerIndex, Vector3Int cellPos, Vector3 cellCenter, Transform playerTransform, float reach)
        {
            CurrentCursorPos = cellCenter;
            CurrentCellPos = cellPos;
            CurrentLayerIndex = layerIndex;
            IsInRange = playerTransform != null ? IsWithinReach(playerTransform, cellCenter, reach) : true;
        }
        
        /// <summary>
        /// 🔥 一次性诊断日志（只在首次调用时输出）
        /// 用于排查预览不显示的问题
        /// </summary>
        private void LogDiagnosticsOnce()
        {
            if (_hasLoggedDiagnostics) return;
            _hasLoggedDiagnostics = true;
            
            Debug.Log("=== [FarmToolPreview] 诊断信息 ===");
            
            // 1. 检查 GhostTilemap
            if (ghostTilemap == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ ghostTilemap 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ ghostTilemap 存在: {ghostTilemap.gameObject.name}");
                Debug.Log($"  - active: {ghostTilemap.gameObject.activeSelf}");
                Debug.Log($"  - parent Grid: {(ghostTilemap.layoutGrid != null ? ghostTilemap.layoutGrid.name : "null")}");
            }
            
            // 2. 检查 GhostTilemapRenderer
            if (ghostTilemapRenderer == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ ghostTilemapRenderer 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ ghostTilemapRenderer 存在");
                Debug.Log($"  - sortingLayerName: {ghostTilemapRenderer.sortingLayerName}");
                Debug.Log($"  - sortingOrder: {ghostTilemapRenderer.sortingOrder}");
                Debug.Log($"  - enabled: {ghostTilemapRenderer.enabled}");
            }
            
            // 3. 检查 CursorRenderer
            if (cursorRenderer == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ cursorRenderer 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ cursorRenderer 存在");
                Debug.Log($"  - sprite: {(cursorRenderer.sprite != null ? cursorRenderer.sprite.name : "null")}");
                Debug.Log($"  - sortingLayerName: {cursorRenderer.sortingLayerName}");
                Debug.Log($"  - sortingOrder: {cursorRenderer.sortingOrder}");
                Debug.Log($"  - color: {cursorRenderer.color}");
                Debug.Log($"  - enabled: {cursorRenderer.enabled}");
                Debug.Log($"  - active: {cursorRenderer.gameObject.activeSelf}");
            }
            
            // 4. 检查 FarmlandBorderManager
            if (FarmlandBorderManager.Instance == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ FarmlandBorderManager.Instance 为 null（场景中没有此组件）");
            }
            else
            {
                Debug.Log("[FarmToolPreview] ✓ FarmlandBorderManager.Instance 存在");
                // 验证 Tile 资源
                FarmlandBorderManager.Instance.ValidateTileResources();
            }
            
            // 5. 检查 FarmTileManager
            if (FarmTileManager.Instance == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ FarmTileManager.Instance 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ FarmTileManager.Instance 存在, LayerCount={FarmTileManager.Instance.LayerCount}");
            }
            
            // 6. 检查 Sorting Layer 是否存在
            Debug.Log("[FarmToolPreview] 检查 Sorting Layers...");
            var sortingLayers = SortingLayer.layers;
            bool hasGround = false, hasEffects = false;
            foreach (var layer in sortingLayers)
            {
                if (layer.name == "Ground") hasGround = true;
                if (layer.name == "Effects") hasEffects = true;
            }
            Debug.Log($"  - Ground: {(hasGround ? "✓ 存在" : "❌ 不存在")}");
            Debug.Log($"  - Effects: {(hasEffects ? "✓ 存在" : "❌ 不存在")}");
            
            Debug.Log("=== 诊断结束 ===");
        }
        
        /// <summary>
        /// 🔥 程序化生成光标 Sprite
        /// 创建一个 16x16 的白色方框（边框 2 像素）
        /// </summary>
        private Sprite CreateProceduralCursorSprite()
        {
            int size = 16;
            int border = 2;
            
            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
            texture.filterMode = FilterMode.Point;
            
            var pixels = new Color32[size * size];
            var white = new Color32(255, 255, 255, 255);
            var transparent = new Color32(0, 0, 0, 0);
            
            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    // 边框区域为白色，内部透明
                    bool isBorder = x < border || x >= size - border || 
                                    y < border || y >= size - border;
                    pixels[y * size + x] = isBorder ? white : transparent;
                }
            }
            
            texture.SetPixels32(pixels);
            texture.Apply();
            
            // 创建 Sprite（16 PPU，与 Tilemap 对齐）
            return Sprite.Create(texture, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), 16f);
        }
        
        /// <summary>
        /// 清除 GhostTilemap 上的所有预览 Tiles
        /// </summary>
        private void ClearGhostTilemap()
        {
            if (ghostTilemap == null) return;
            
            foreach (var pos in currentPreviewPositions)
            {
                ghostTilemap.SetTile(pos, null);
            }
            currentPreviewPositions.Clear();
        }
        
        /// <summary>
        /// 更新光标位置和颜色
        /// </summary>
        private void UpdateCursor(int layerIndex, Vector3Int cellPos)
        {
            if (cursorRenderer == null) return;
            
            // 获取格子中心世界坐标
            var tilemaps = FarmTileManager.Instance?.GetLayerTilemaps(layerIndex);
            Vector3 worldPos;
            
            if (tilemaps != null)
            {
                worldPos = tilemaps.GetCellCenterWorld(cellPos);
            }
            else
            {
                // 回退：使用 PlacementGridCalculator
                worldPos = PlacementGridCalculator.GetCellCenter(new Vector3(cellPos.x, cellPos.y, 0));
            }
            
            cursorRenderer.transform.position = worldPos;
            
            // 设置颜色
            Color color;
            if (!isHoeMode && currentState == FarmPreviewState.Valid)
            {
                // 水壶有效 = 蓝色
                color = wateringColor;
            }
            else if (currentState == FarmPreviewState.Valid)
            {
                // 锄头有效 = 绿色
                color = validColor;
            }
            else
            {
                // 无效 = 红色
                color = invalidColor;
            }
            
            cursorRenderer.color = color;
        }
        
        /// <summary>
        /// 🔥 新增：更新种子模式的光标
        /// </summary>
        private void UpdateCursorForSeed(Vector3 worldPos, bool isValid)
        {
            if (cursorRenderer == null) return;
            
            cursorRenderer.transform.position = worldPos;
            cursorRenderer.color = isValid ? seedValidColor : seedInvalidColor;
        }
        
        /// <summary>
        /// 🔥 新增：更新 Sorting Layer（跟随玩家楼层）
        /// </summary>
        private void UpdateSortingLayer(Transform playerTransform)
        {
            if (playerTransform == null) return;
            
            string playerSortingLayer = PlacementLayerDetector.GetPlayerSortingLayer(playerTransform);
            
            // 只在 Layer 变化时更新
            if (playerSortingLayer != currentSortingLayer)
            {
                currentSortingLayer = playerSortingLayer;
                
                // 更新 GhostTilemap 的 Sorting Layer
                if (ghostTilemapRenderer != null)
                {
                    ghostTilemapRenderer.sortingLayerName = currentSortingLayer;
                }
                
                // 更新 CursorRenderer 的 Sorting Layer
                if (cursorRenderer != null)
                {
                    cursorRenderer.sortingLayerName = currentSortingLayer;
                }
                
                if (showDebugInfo)
                {
                    Debug.Log($"[FarmToolPreview] Sorting Layer 更新为: {currentSortingLayer}");
                }
            }
        }
        
        /// <summary>
        /// 🔥 新增：获取玩家中心位置
        /// </summary>
        private Vector2 GetPlayerCenter(Transform playerTransform)
        {
            if (playerTransform == null) return Vector2.zero;
            
            var collider = playerTransform.GetComponent<Collider2D>();
            return collider != null ? (Vector2)collider.bounds.center : (Vector2)playerTransform.position;
        }
        
        /// <summary>
        /// 🔥 新增：获取格子中心世界坐标
        /// </summary>
        private Vector3 GetCellCenterWorld(int layerIndex, Vector3Int cellPos)
        {
            var tilemaps = FarmTileManager.Instance?.GetLayerTilemaps(layerIndex);
            if (tilemaps != null)
            {
                return tilemaps.GetCellCenterWorld(cellPos);
            }
            
            // 回退：使用 PlacementGridCalculator
            return PlacementGridCalculator.GetCellCenter(new Vector3(cellPos.x + 0.5f, cellPos.y + 0.5f, 0));
        }
        
        /// <summary>
        /// 🔥 新增：检查是否在使用距离内
        /// </summary>
        private bool IsWithinReach(Transform playerTransform, Vector3 targetPos, float reach)
        {
            Vector2 playerCenter = GetPlayerCenter(playerTransform);
            float distance = Vector2.Distance(playerCenter, targetPos);
            return distance <= reach;
        }
        
        #endregion
    }
}
