using UnityEngine;
using UnityEngine.Tilemaps;
using System.Collections.Generic;

namespace FarmGame.Farm
{
    /// <summary>
    /// 农田工具预览组件
    /// 负责显示锄头/水壶的预览效果
    /// 
    /// 特性：
    /// - 自生能力：Awake 时自动创建缺失的 GhostTilemap 和 CursorRenderer
    /// - 1+8 预览：锄头显示中心块 + 周围 8 格边界变化
    /// - 颜色反馈：绿色=可用，红色=不可用，蓝色=浇水
    /// </summary>
    public class FarmToolPreview : MonoBehaviour
    {
        #region 单例（Lazy Singleton）
        
        private static FarmToolPreview _instance;
        
        /// <summary>
        /// 单例访问器（Lazy Singleton）
        /// 如果场景中没有 FarmToolPreview，会自动创建一个
        /// </summary>
        public static FarmToolPreview Instance
        {
            get
            {
                if (_instance == null)
                {
                    // 先尝试在场景中查找
                    _instance = FindFirstObjectByType<FarmToolPreview>();
                    
                    if (_instance == null)
                    {
                        // 🔥 真正的自生能力：如果场景没有，直接创建一个
                        var go = new GameObject("FarmToolPreview_AutoGenerated");
                        _instance = go.AddComponent<FarmToolPreview>();
                        Debug.Log("[FarmToolPreview] 自动创建实例（场景中未找到）");
                    }
                }
                return _instance;
            }
        }
        
        #endregion
        
        #region 预览状态枚举
        
        public enum FarmPreviewState
        {
            Hidden,     // 隐藏
            Valid,      // 有效（绿色）
            Invalid     // 无效（红色）
        }
        
        // 🔥 9.0.5 新增：浇水失败原因
        public enum WateringFailureReason
        {
            None,           // 无失败
            NoFarmland,     // 没有耕地数据
            NotTilled,      // 未耕作
            AlreadyWatered, // 已浇水
            HasObstacle,    // 有障碍物
            ManagerNull     // FarmTileManager 为 null
        }
        
        #endregion
        
        #region 配置
        
        [Header("光标配置")]
        [Tooltip("光标 Sprite（方形框）")]
        [SerializeField] private Sprite cursorSprite;
        
        [Tooltip("有效时的颜色（绿色）")]
        [SerializeField] private Color validColor = new Color(0f, 1f, 0f, 0.5f);
        
        [Tooltip("无效时的颜色（红色）")]
        [SerializeField] private Color invalidColor = new Color(1f, 0f, 0f, 0.5f);
        
        [Tooltip("浇水时的颜色（蓝色）")]
        [SerializeField] private Color wateringColor = new Color(0f, 0.5f, 1f, 0.5f);
        
        [Header("预览透明度")]
        [SerializeField, Range(0.1f, 1f)] private float previewAlpha = 0.5f;
        
        [Header("Debug")]
        [SerializeField] private bool showDebugInfo = false;
        
        #endregion
        
        #region 运行时引用（自动创建）
        
        private Tilemap ghostTilemap;
        private TilemapRenderer ghostTilemapRenderer;
        private SpriteRenderer cursorRenderer;
        
        #endregion
        
        #region 状态
        
        private FarmPreviewState currentState = FarmPreviewState.Hidden;
        private Vector3Int lastCellPosition;
        private int lastLayerIndex = -1;
        private bool isHoeMode = false; // true=锄头, false=水壶
        private bool isSeedMode = false; // 🔥 新增：种子模式
        
        // 🔥 新增：当前 Sorting Layer 缓存
        private string currentSortingLayer = "Layer 1";
        
        // 🔥 9.0.4 新增：公开属性供 GameInputManager 查询
        /// <summary>
        /// 当前目标是否在使用距离内
        /// </summary>
        public bool IsInRange { get; private set; }
        
        /// <summary>
        /// 当前光标位置（格子中心世界坐标）
        /// </summary>
        public Vector3 CurrentCursorPos { get; private set; }
        
        /// <summary>
        /// 当前目标的格子坐标
        /// </summary>
        public Vector3Int CurrentCellPos { get; private set; }
        
        /// <summary>
        /// 当前目标的楼层索引
        /// </summary>
        public int CurrentLayerIndex { get; private set; }
        
        // 🔥 新增：种子颜色
        [Header("种子预览配置")]
        [SerializeField] private Color seedValidColor = new Color(0f, 0.8f, 0.2f, 0.6f);
        [SerializeField] private Color seedInvalidColor = new Color(1f, 0.2f, 0f, 0.6f);
        
        // 缓存当前预览的 Tiles（用于清除）
        private HashSet<Vector3Int> currentPreviewPositions = new HashSet<Vector3Int>();
        
        // 🔥 诊断日志去重标志
        private bool _hasLoggedDiagnostics = false;
        private bool _hasLoggedPreviewTiles = false;
        
        // === 🔴 补丁004：锁定机制已移除（模块A） ===
        
        // 🔴 补丁004 模块B：差异化 ghost tile 数据缓存（供入队时复制）
        private Dictionary<Vector3Int, TileBase> _currentGhostTileData;
        /// <summary>
        /// 当前 ghost 预览的差异化 tile 数据快照（耕地模式）。
        /// 入队时复制此数据到队列预览，确保三层数据一致。
        /// </summary>
        public Dictionary<Vector3Int, TileBase> CurrentGhostTileData => _currentGhostTileData;
        
        // 🔴 补丁004 模块C：浇水 ghost 缓存（进入新格子才随机）
        private Vector3Int _lastWateringCellPos = new Vector3Int(int.MinValue, int.MinValue, 0);
        private int _cachedPuddleVariant = -1;
        /// <summary>
        /// 当前浇水 ghost 的 puddleVariant（供入队时复制）。
        /// </summary>
        public int CurrentPuddleVariant => _cachedPuddleVariant;
        
        // 🔥 9.0.5 新增：浇水失败原因
        public WateringFailureReason LastWateringFailure { get; private set; } = WateringFailureReason.None;
        
        // === 🔴 补丁003 模块H：预览系统全面改造 ===
        
        // 双 Tilemap 分离（CP-H4）
        private Tilemap queuePreviewTilemap;
        private TilemapRenderer queuePreviewTilemapRenderer;
        
        // 🔴 V3 模块M（CP-M1）：shader 颜色叠加 Material（替代方案C的 SpriteRenderer 覆盖层）
        private Material previewOverlayMaterial;
        
        // 种子预览 — 复刻放置系统（CP-H3）
        private SpriteRenderer seedPreviewRenderer;
        private SpriteRenderer seedGridRenderer;
        private Sprite gridSprite;  // 程序化格子方框 sprite
        
        // 种子队列预览对象池（CP-H6）
        private List<SpriteRenderer> seedQueuePool = new List<SpriteRenderer>();
        private List<(Vector3Int cellPos, SpriteRenderer renderer)> activeSeedQueuePreviews = new List<(Vector3Int, SpriteRenderer)>();
        
        // 队列预览位置缓存
        private HashSet<Vector3Int> queuePreviewPositions = new HashSet<Vector3Int>();
        
        // 🔴 V3 模块K（CP-K1）：耕地队列 tile 组追踪（中心点 → 关联的所有 tile 位置）
        private Dictionary<Vector3Int, List<Vector3Int>> tillQueueTileGroups = new Dictionary<Vector3Int, List<Vector3Int>>();
        
        // 🔴 补丁004 模块D：执行预览追踪（正在执行动画的操作，受保护不被 WASD 清除）
        private Dictionary<Vector3Int, List<Vector3Int>> executingTileGroups = new Dictionary<Vector3Int, List<Vector3Int>>();
        private HashSet<Vector3Int> executingWaterPositions = new HashSet<Vector3Int>();
        private List<(Vector3Int cellPos, SpriteRenderer renderer)> executingSeedPreviews = new List<(Vector3Int, SpriteRenderer)>();
        
        // 颜色配置
        [Header("补丁003 覆盖层颜色")]
        [SerializeField] private Color overlayValidColor = new Color(0f, 1f, 0f, 0.3f);
        [SerializeField] private Color overlayInvalidColor = new Color(1f, 0f, 0f, 0.3f);
        [SerializeField] private float queuePreviewAlpha = 0.5f;
        
        #endregion
        
        #region 生命周期
        
        private void Awake()
        {
            if (_instance == null)
            {
                _instance = this;
                EnsureComponents();
            }
            else if (_instance != this)
            {
                Destroy(gameObject);
            }
        }
        
        private void OnDestroy()
        {
            if (_instance == this)
            {
                _instance = null;
            }
        }
        
        /// <summary>
        /// 自生能力：确保所有必要组件存在
        /// </summary>
        private void EnsureComponents()
        {
            // 🔥 首先确保有 Grid 组件（Tilemap 必须在 Grid 下才能正确显示）
            var grid = GetComponent<Grid>();
            if (grid == null)
            {
                grid = gameObject.AddComponent<Grid>();
                grid.cellSize = new Vector3(1f, 1f, 0f); // 标准 1x1 格子
                grid.cellGap = Vector3.zero;
                grid.cellLayout = GridLayout.CellLayout.Rectangle;
                grid.cellSwizzle = GridLayout.CellSwizzle.XYZ;
            }
            
            // 1. 确保 GhostTilemap 存在
            if (ghostTilemap == null)
            {
                var ghostGO = transform.Find("GhostTilemap");
                if (ghostGO == null)
                {
                    ghostGO = new GameObject("GhostTilemap").transform;
                    ghostGO.SetParent(transform);
                    ghostGO.localPosition = Vector3.zero;
                }
                
                ghostTilemap = ghostGO.GetComponent<Tilemap>();
                if (ghostTilemap == null)
                {
                    ghostTilemap = ghostGO.gameObject.AddComponent<Tilemap>();
                }
                
                ghostTilemapRenderer = ghostGO.GetComponent<TilemapRenderer>();
                if (ghostTilemapRenderer == null)
                {
                    ghostTilemapRenderer = ghostGO.gameObject.AddComponent<TilemapRenderer>();
                }
                
                // 设置 Sorting Layer（使用项目中存在的 Layer 1，高 sortingOrder 确保在地面之上）
                ghostTilemapRenderer.sortingLayerName = "Layer 1";
                ghostTilemapRenderer.sortingOrder = 9999; // 极高值确保在所有地面 Tile 之上
                
                // 设置透明度
                ghostTilemap.color = new Color(1f, 1f, 1f, previewAlpha);
                
                if (showDebugInfo)
                    Debug.Log("[FarmToolPreview] 自动创建 GhostTilemap（含 Grid）");
            }
            
            // 2. 确保 CursorRenderer 存在
            if (cursorRenderer == null)
            {
                var cursorGO = transform.Find("CursorRenderer");
                if (cursorGO == null)
                {
                    cursorGO = new GameObject("CursorRenderer").transform;
                    cursorGO.SetParent(transform);
                    cursorGO.localPosition = Vector3.zero;
                }
                
                cursorRenderer = cursorGO.GetComponent<SpriteRenderer>();
                if (cursorRenderer == null)
                {
                    cursorRenderer = cursorGO.gameObject.AddComponent<SpriteRenderer>();
                }
                
                // 设置 Sorting Layer（使用项目中存在的 Layer 1，高 sortingOrder 确保在预览 Tilemap 之上）
                cursorRenderer.sortingLayerName = "Layer 1";
                cursorRenderer.sortingOrder = 10000; // 比 ghostTilemap 更高
                
                // 设置 Sprite（如果没有配置，程序化生成一个白色方框）
                if (cursorSprite != null)
                {
                    cursorRenderer.sprite = cursorSprite;
                }
                else
                {
                    // 🔥 程序化生成光标 Sprite（1x1 白色 Texture）
                    cursorRenderer.sprite = CreateProceduralCursorSprite();
                    if (showDebugInfo)
                        Debug.Log("[FarmToolPreview] 程序化生成光标 Sprite（未配置 cursorSprite）");
                }
                
                if (showDebugInfo)
                    Debug.Log("[FarmToolPreview] 自动创建 CursorRenderer");
            }
            
            // === 🔴 补丁003 模块H：新增组件初始化 ===
            
            // 3. queuePreviewTilemap（队列预览专用）
            if (queuePreviewTilemap == null)
            {
                var queueGO = transform.Find("QueuePreviewTilemap");
                if (queueGO == null)
                {
                    queueGO = new GameObject("QueuePreviewTilemap").transform;
                    queueGO.SetParent(transform, false);
                    queueGO.localPosition = Vector3.zero;
                }
                queuePreviewTilemap = queueGO.GetComponent<Tilemap>();
                if (queuePreviewTilemap == null)
                    queuePreviewTilemap = queueGO.gameObject.AddComponent<Tilemap>();
                queuePreviewTilemapRenderer = queueGO.GetComponent<TilemapRenderer>();
                if (queuePreviewTilemapRenderer == null)
                    queuePreviewTilemapRenderer = queueGO.gameObject.AddComponent<TilemapRenderer>();
                queuePreviewTilemapRenderer.sortingLayerName = "Layer 1";
                queuePreviewTilemapRenderer.sortingOrder = 9998;
                queuePreviewTilemap.color = new Color(1f, 1f, 1f, queuePreviewAlpha);
            }
            
            // 4. 🔴 V3 模块M（CP-M1）：加载 FarmPreviewOverlay shader 并创建 Material
            if (previewOverlayMaterial == null)
            {
                var shader = Shader.Find("Custom/FarmPreviewOverlay");
                if (shader != null)
                {
                    previewOverlayMaterial = new Material(shader);
                    previewOverlayMaterial.SetColor("_OverlayColor", Color.clear); // 默认无叠加
                }
                else
                {
                    Debug.LogWarning("[FarmToolPreview] FarmPreviewOverlay shader 未找到，ghostTilemap 将使用默认 Material");
                }
            }
            // 赋给 ghostTilemapRenderer
            if (previewOverlayMaterial != null && ghostTilemapRenderer != null)
            {
                ghostTilemapRenderer.material = previewOverlayMaterial;
            }
            
            // 5. 程序化格子 Sprite 生成（种子预览用）
            if (gridSprite == null)
                gridSprite = CreateGridSprite();
            
            // 6. 种子预览组件
            if (seedGridRenderer == null)
            {
                var seedGridGO = new GameObject("SeedGridRenderer");
                seedGridGO.transform.SetParent(transform, false);
                seedGridRenderer = seedGridGO.AddComponent<SpriteRenderer>();
                seedGridRenderer.sprite = gridSprite;
                seedGridRenderer.sortingLayerName = "Layer 1";
                seedGridRenderer.sortingOrder = 10000;
                seedGridRenderer.enabled = false;
            }
            if (seedPreviewRenderer == null)
            {
                var seedPreviewGO = new GameObject("SeedPreviewRenderer");
                seedPreviewGO.transform.SetParent(transform, false);
                seedPreviewRenderer = seedPreviewGO.AddComponent<SpriteRenderer>();
                seedPreviewRenderer.sortingLayerName = "Layer 1";
                seedPreviewRenderer.sortingOrder = 10001;
                seedPreviewRenderer.enabled = false;
            }
        }
        
        #endregion
        
        #region 公开接口
        
        // === 🔴 补丁004 模块A：锁定机制公开接口已移除 ===
        
        // 🔴 补丁004 模块A：LockPosition 已移除（ghost 永不锁定，每帧跟随鼠标）
        
        // 🔴 补丁004 模块A：UnlockPosition 已移除
        
        /// <summary>
        /// 🔥 重构：更新锄头预览
        /// 新增参数：playerTransform 和 reach 用于距离检测
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        /// <param name="layerIndex">楼层索引</param>
        /// <param name="cellPos">格子坐标</param>
        /// <param name="playerTransform">玩家 Transform（用于距离检测和 Layer 同步）</param>
        /// <param name="reach">工具使用距离</param>
        public void UpdateHoePreview(int layerIndex, Vector3Int cellPos, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = true;
            isSeedMode = false;
            
            // 🔥 一次性诊断日志（只在首次调用时输出）
            LogDiagnosticsOnce();
            
            // 🔥 Step 1: 更新 Sorting Layer（跟随玩家楼层）
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取格子中心世界坐标
            Vector3 cellCenter = GetCellCenterWorld(layerIndex, cellPos);
            
            // 🔥 Step 2: 障碍物检测（使用 HasFarmingObstacle，不检测 Player）
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(cellCenter);
            
            // 🔥 Step 3: 检查是否可以锄地
            bool canTill = FarmTileManager.Instance != null && 
                           FarmTileManager.Instance.CanTillAt(layerIndex, cellPos);
            
            // 🔥 10.X 纠正：通过 FarmTileData.cropController 查找枯萎作物（替代 CropManager.GetCrop）
            bool canClearWithered = false;
            if (!canTill && FarmTileManager.Instance != null)
            {
                var tileData = FarmTileManager.Instance.GetTileData(layerIndex, cellPos);
                if (tileData?.cropController != null && tileData.cropController.GetState() == CropState.WitheredImmature)
                    canClearWithered = true;
            }
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && (canTill || canClearWithered);
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, cellCenter, playerTransform, reach);
            
            // 🔴 补丁004 模块A：移除 _isLocked 检查，ghost 每帧更新
            
            // 🔴 V3 模块M（CP-M2）：隐藏种子预览
            if (seedGridRenderer != null) seedGridRenderer.enabled = false;
            if (seedPreviewRenderer != null) seedPreviewRenderer.enabled = false;
            
            // 清除旧预览
            ClearGhostTilemap();
            
            // 🔴 V3 模块M：耕地不需要方框光标
            if (cursorRenderer != null) cursorRenderer.enabled = false;
            
            // 如果可以锄地，显示差异化预览（🔴 补丁004 模块B：对比实际 tilemap 只显示变化 tile）
            if (canTill && FarmlandBorderManager.Instance != null)
            {
                var previewTiles = FarmlandBorderManager.Instance.GetPreviewTiles(layerIndex, cellPos);
                
                // 🔥 诊断：检查 previewTiles 是否为空（一次性输出，不依赖 showDebugInfo）
                if (!_hasLoggedPreviewTiles)
                {
                    _hasLoggedPreviewTiles = true;
                    Debug.Log($"[FarmToolPreview] GetPreviewTiles 返回 {previewTiles.Count} 个 Tile");
                    foreach (var kvp in previewTiles)
                    {
                        Debug.Log($"  - {kvp.Key}: {(kvp.Value != null ? kvp.Value.name : "null")}");
                    }
                }
                
                // 🔴 补丁004 模块B（CP-B1）：获取实际 tilemap 用于差异对比
                var tilemaps = FarmTileManager.Instance?.GetLayerTilemaps(layerIndex);
                Tilemap actualCenterTilemap = tilemaps?.farmlandCenterTilemap;
                Tilemap actualBorderTilemap = tilemaps?.farmlandBorderTilemap;
                
                // 缓存差异化结果供入队时复制
                if (_currentGhostTileData == null)
                    _currentGhostTileData = new Dictionary<Vector3Int, TileBase>();
                else
                    _currentGhostTileData.Clear();
                
                foreach (var kvp in previewTiles)
                {
                    if (kvp.Value == null) continue;
                    
                    // 🔴 补丁004 模块B（CP-B1）：差异化过滤 — 对比实际 Tilemap
                    // 中心块对比 farmlandCenterTilemap，边界对比 farmlandBorderTilemap
                    TileBase actualTile;
                    if (kvp.Key == cellPos)
                        actualTile = actualCenterTilemap?.GetTile(kvp.Key);
                    else
                        actualTile = actualBorderTilemap?.GetTile(kvp.Key);
                    
                    if (kvp.Value == actualTile) continue;  // 相同则跳过
                    
                    ghostTilemap.SetTile(kvp.Key, kvp.Value);
                    currentPreviewPositions.Add(kvp.Key);
                    _currentGhostTileData[kvp.Key] = kvp.Value;
                }
            }
            else
            {
                // 不可锄地时清空缓存
                _currentGhostTileData?.Clear();
                
                if (!_hasLoggedPreviewTiles)
                {
                    _hasLoggedPreviewTiles = true;
                    Debug.Log($"[FarmToolPreview] 跳过 1+8 预览: canTill={canTill}, BorderManager={(FarmlandBorderManager.Instance != null ? "存在" : "null")}");
                }
            }
            
            // 🔴 V3 模块M（CP-M2）：根据 isValid 设置 ghostTilemap 的 shader 叠加色
            if (previewOverlayMaterial != null)
            {
                previewOverlayMaterial.SetColor("_OverlayColor", isValid ? overlayValidColor : overlayInvalidColor);
            }
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 显示
            Show();
        }
        
        /// <summary>
        /// 🔥 重构：更新水壶预览
        /// 新增参数：playerTransform 和 reach 用于距离检测
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        public void UpdateWateringPreview(int layerIndex, Vector3Int cellPos, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = false;
            isSeedMode = false;
            
            // 🔥 Step 1: 更新 Sorting Layer
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取格子中心世界坐标
            Vector3 cellCenter = GetCellCenterWorld(layerIndex, cellPos);
            
            // 🔥 Step 2: 障碍物检测
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(cellCenter);
            
            // 🔥 Step 3: 检查是否可以浇水
            var tileData = FarmTileManager.Instance?.GetTileData(layerIndex, cellPos);
            bool canWater = tileData != null && 
                            tileData.isTilled && 
                            !tileData.wateredToday;
            
            // 🔥 9.0.5：记录浇水失败原因
            if (hasObstacle)
                LastWateringFailure = WateringFailureReason.HasObstacle;
            else if (FarmTileManager.Instance == null)
                LastWateringFailure = WateringFailureReason.ManagerNull;
            else if (tileData == null)
                LastWateringFailure = WateringFailureReason.NoFarmland;
            else if (!tileData.isTilled)
                LastWateringFailure = WateringFailureReason.NotTilled;
            else if (tileData.wateredToday)
                LastWateringFailure = WateringFailureReason.AlreadyWatered;
            else
                LastWateringFailure = WateringFailureReason.None;
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && canWater;
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, cellCenter, playerTransform, reach);
            
            // 🔴 补丁004 模块A：移除 _isLocked 检查，ghost 每帧更新
            
            // 🔴 V3 模块M（CP-M3）：隐藏种子预览
            if (seedGridRenderer != null) seedGridRenderer.enabled = false;
            if (seedPreviewRenderer != null) seedPreviewRenderer.enabled = false;
            
            // 清除旧预览
            ClearGhostTilemap();
            
            // 🔴 V3 模块M：浇水不需要方框光标
            if (cursorRenderer != null) cursorRenderer.enabled = false;
            
            // 🔴 补丁004 模块C（CP-C1）：有效时在 ghostTilemap 上显示水渍 tile 预览（进入新格子才随机）
            if (isValid)
            {
                // 🔴 补丁004 模块C：进入新格子才随机
                if (cellPos != _lastWateringCellPos)
                {
                    var puddleTiles = FarmVisualManager.Instance?.GetPuddleTiles();
                    int count = puddleTiles != null ? puddleTiles.Length : 3;
                    _cachedPuddleVariant = Random.Range(0, count);
                    _lastWateringCellPos = cellPos;
                }
                
                // 使用缓存的 variant 获取确定性 tile
                var tiles = FarmVisualManager.Instance?.GetPuddleTiles();
                if (tiles != null && _cachedPuddleVariant >= 0 && _cachedPuddleVariant < tiles.Length)
                {
                    ghostTilemap.SetTile(cellPos, tiles[_cachedPuddleVariant]);
                    currentPreviewPositions.Add(cellPos);
                }
            }
            
            // 🔴 V3 模块M（CP-M3）：根据 isValid 设置 ghostTilemap 的 shader 叠加色
            if (previewOverlayMaterial != null)
            {
                previewOverlayMaterial.SetColor("_OverlayColor", isValid ? overlayValidColor : overlayInvalidColor);
            }
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 显示
            Show();
        }
        
        /// <summary>
        /// 🔥 新增：更新种子预览
        /// 只显示红/绿光标，隐藏 GhostTilemap
        /// 🔥 9.0.4：IsValid 不再包含距离判断，距离状态单独记录到 IsInRange
        /// </summary>
        /// <param name="alignedPos">对齐后的世界坐标（格子中心）</param>
        /// <param name="seedData">种子数据</param>
        /// <param name="playerTransform">玩家 Transform</param>
        /// <param name="reach">种植距离</param>
        public void UpdateSeedPreview(Vector3 alignedPos, FarmGame.Data.SeedData seedData, Transform playerTransform = null, float reach = 1.5f)
        {
            isHoeMode = false;
            isSeedMode = true;
            
            // 🔥 Step 1: 更新 Sorting Layer
            if (playerTransform != null)
            {
                UpdateSortingLayer(playerTransform);
            }
            
            // 获取楼层和格子坐标
            var farmTileManager = FarmTileManager.Instance;
            if (farmTileManager == null)
            {
                currentState = FarmPreviewState.Invalid;
                IsInRange = false;
                UpdateCursorForSeed(alignedPos, false);
                Show();
                return;
            }
            
            int layerIndex = farmTileManager.GetCurrentLayerIndex(alignedPos);
            var tilemaps = farmTileManager.GetLayerTilemaps(layerIndex);
            
            if (tilemaps == null)
            {
                currentState = FarmPreviewState.Invalid;
                IsInRange = false;
                UpdateCursorForSeed(alignedPos, false);
                Show();
                return;
            }
            
            Vector3Int cellPos = tilemaps.WorldToCell(alignedPos);
            
            // 🔴 V3 模块J（CP-J1）：使用 Tilemap 原生坐标替代 PlacementGridCalculator 坐标
            Vector3 correctCenter = GetCellCenterWorld(layerIndex, cellPos);
            
            // 🔥 Step 2: 障碍物检测
            bool hasObstacle = PlacementValidator.HasFarmingObstacle(correctCenter);
            
            // 🔥 Step 3: 检查是否可以种植
            var tileData = farmTileManager.GetTileData(layerIndex, cellPos);
            bool canPlant = tileData != null && tileData.CanPlant();
            
            // 🔥 Step 5: 检查季节（可选）
            bool correctSeason = true;
            if (seedData != null && TimeManager.Instance != null)
            {
                if (seedData.season != FarmGame.Data.Season.AllSeason)
                {
                    var currentSeason = TimeManager.Instance.GetSeason();
                    correctSeason = (int)seedData.season == (int)currentSeason;
                }
            }
            
            // 🔥 9.0.4 修改：IsValid 不再包含距离判断
            bool isValid = !hasObstacle && canPlant && correctSeason;
            
            // 更新状态
            currentState = isValid ? FarmPreviewState.Valid : FarmPreviewState.Invalid;
            
            // 🔥 9.0.5：永远更新实时数据（不管是否锁定）
            UpdateRealtimeData(layerIndex, cellPos, correctCenter, playerTransform, reach);
            
            // 🔴 补丁004 模块A：移除 _isLocked 检查，ghost 每帧更新
            
            // 🔴 V3 模块M（CP-M6）：重置 shader 叠加色（种子预览不使用 shader）
            if (previewOverlayMaterial != null)
                previewOverlayMaterial.SetColor("_OverlayColor", Color.clear);
            
            // 清除旧预览
            ClearGhostTilemap();
            if (ghostTilemap != null)
            {
                ghostTilemap.gameObject.SetActive(false);
            }
            
            // 🔴 补丁003：隐藏 cursorRenderer（底部格子方框已替代）
            if (cursorRenderer != null) cursorRenderer.enabled = false;
            
            // 🔴 补丁003：底部格子方框（复刻 PlacementGridCell）
            if (seedGridRenderer != null)
            {
                seedGridRenderer.enabled = true;
                seedGridRenderer.transform.position = correctCenter;  // 🔴 V3 模块J：使用 Tilemap 原生坐标
                seedGridRenderer.color = isValid
                    ? new Color(0f, 1f, 0f, 0.4f)   // 绿色
                    : new Color(1f, 0f, 0f, 0.4f);   // 红色
            }
            
            // 🔴 补丁003：作物第一阶段 sprite 预览
            if (seedPreviewRenderer != null)
            {
                seedPreviewRenderer.enabled = true;
                var cropSprite = seedData?.cropPrefab?.GetComponentInChildren<CropController>()?.GetFirstStageSprite();
                if (cropSprite != null)
                    seedPreviewRenderer.sprite = cropSprite;
                seedPreviewRenderer.transform.position = correctCenter;  // 🔴 V3 模块J：使用 Tilemap 原生坐标
                seedPreviewRenderer.color = isValid
                    ? new Color(1f, 1f, 1f, 0.7f)              // 原色 + alpha
                    : new Color(1f, 0.5f, 0.5f, 0.7f);         // 偏红 + alpha
            }
            
            // 记录位置
            lastCellPosition = cellPos;
            lastLayerIndex = layerIndex;
            
            // 🔴 补丁003：种子预览通过 seedGridRenderer + seedPreviewRenderer 显示，不再依赖 cursorRenderer
            Show();
        }
        
        /// <summary>
        /// 显示预览
        /// </summary>
        public void Show()
        {
            if (!isSeedMode && ghostTilemap != null)
                ghostTilemap.gameObject.SetActive(true);
            if (cursorRenderer != null)
                cursorRenderer.gameObject.SetActive(true);
        }
        
        /// <summary>
        /// 隐藏预览
        /// </summary>
        public void Hide()
        {
            currentState = FarmPreviewState.Hidden;
            isSeedMode = false;
            
            ClearGhostTilemap();
            
            if (ghostTilemap != null)
                ghostTilemap.gameObject.SetActive(false);
            if (cursorRenderer != null)
                cursorRenderer.gameObject.SetActive(false);
            
            // 🔴 V3 模块M（CP-M5）：隐藏种子预览组件
            if (seedGridRenderer != null) seedGridRenderer.enabled = false;
            if (seedPreviewRenderer != null) seedPreviewRenderer.enabled = false;
            // 🔴 V3 模块M：重置 shader 叠加色
            if (previewOverlayMaterial != null)
                previewOverlayMaterial.SetColor("_OverlayColor", Color.clear);
            // 🔴 补丁004 模块C（CP-C4）：重置浇水缓存
            _lastWateringCellPos = new Vector3Int(int.MinValue, int.MinValue, 0);
            _cachedPuddleVariant = -1;
            // 注意：不清空队列预览（Hide 只隐藏鼠标跟随预览）
        }
        
        /// <summary>
        /// 检查当前预览是否有效
        /// </summary>
        public bool IsValid()
        {
            return currentState == FarmPreviewState.Valid;
        }
        
        /// <summary>
        /// 获取当前预览状态
        /// </summary>
        public FarmPreviewState GetState()
        {
            return currentState;
        }
        
        #endregion
        
        #region 内部方法
        
        /// <summary>
        /// 🔥 9.0.5 新增：轻量级实时数据更新（不触碰视觉渲染）
        /// 锁定状态下也会被调用，确保 GameInputManager 能读到最新的鼠标位置数据
        /// </summary>
        private void UpdateRealtimeData(int layerIndex, Vector3Int cellPos, Vector3 cellCenter, Transform playerTransform, float reach)
        {
            CurrentCursorPos = cellCenter;
            CurrentCellPos = cellPos;
            CurrentLayerIndex = layerIndex;
            IsInRange = playerTransform != null ? IsWithinReach(playerTransform, cellCenter, reach) : true;
        }
        
        /// <summary>
        /// 🔥 一次性诊断日志（只在首次调用时输出）
        /// 用于排查预览不显示的问题
        /// </summary>
        private void LogDiagnosticsOnce()
        {
            if (_hasLoggedDiagnostics) return;
            _hasLoggedDiagnostics = true;
            
            Debug.Log("=== [FarmToolPreview] 诊断信息 ===");
            
            // 1. 检查 GhostTilemap
            if (ghostTilemap == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ ghostTilemap 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ ghostTilemap 存在: {ghostTilemap.gameObject.name}");
                Debug.Log($"  - active: {ghostTilemap.gameObject.activeSelf}");
                Debug.Log($"  - parent Grid: {(ghostTilemap.layoutGrid != null ? ghostTilemap.layoutGrid.name : "null")}");
            }
            
            // 2. 检查 GhostTilemapRenderer
            if (ghostTilemapRenderer == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ ghostTilemapRenderer 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ ghostTilemapRenderer 存在");
                Debug.Log($"  - sortingLayerName: {ghostTilemapRenderer.sortingLayerName}");
                Debug.Log($"  - sortingOrder: {ghostTilemapRenderer.sortingOrder}");
                Debug.Log($"  - enabled: {ghostTilemapRenderer.enabled}");
            }
            
            // 3. 检查 CursorRenderer
            if (cursorRenderer == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ cursorRenderer 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ cursorRenderer 存在");
                Debug.Log($"  - sprite: {(cursorRenderer.sprite != null ? cursorRenderer.sprite.name : "null")}");
                Debug.Log($"  - sortingLayerName: {cursorRenderer.sortingLayerName}");
                Debug.Log($"  - sortingOrder: {cursorRenderer.sortingOrder}");
                Debug.Log($"  - color: {cursorRenderer.color}");
                Debug.Log($"  - enabled: {cursorRenderer.enabled}");
                Debug.Log($"  - active: {cursorRenderer.gameObject.activeSelf}");
            }
            
            // 4. 检查 FarmlandBorderManager
            if (FarmlandBorderManager.Instance == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ FarmlandBorderManager.Instance 为 null（场景中没有此组件）");
            }
            else
            {
                Debug.Log("[FarmToolPreview] ✓ FarmlandBorderManager.Instance 存在");
                // 验证 Tile 资源
                FarmlandBorderManager.Instance.ValidateTileResources();
            }
            
            // 5. 检查 FarmTileManager
            if (FarmTileManager.Instance == null)
            {
                Debug.LogError("[FarmToolPreview] ❌ FarmTileManager.Instance 为 null");
            }
            else
            {
                Debug.Log($"[FarmToolPreview] ✓ FarmTileManager.Instance 存在, LayerCount={FarmTileManager.Instance.LayerCount}");
            }
            
            // 6. 检查 Sorting Layer 是否存在
            Debug.Log("[FarmToolPreview] 检查 Sorting Layers...");
            var sortingLayers = SortingLayer.layers;
            bool hasGround = false, hasEffects = false;
            foreach (var layer in sortingLayers)
            {
                if (layer.name == "Ground") hasGround = true;
                if (layer.name == "Effects") hasEffects = true;
            }
            Debug.Log($"  - Ground: {(hasGround ? "✓ 存在" : "❌ 不存在")}");
            Debug.Log($"  - Effects: {(hasEffects ? "✓ 存在" : "❌ 不存在")}");
            
            Debug.Log("=== 诊断结束 ===");
        }
        
        /// <summary>
        /// 🔥 程序化生成光标 Sprite
        /// 创建一个 16x16 的白色方框（边框 2 像素）
        /// </summary>
        private Sprite CreateProceduralCursorSprite()
        {
            int size = 16;
            int border = 2;
            
            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
            texture.filterMode = FilterMode.Point;
            
            var pixels = new Color32[size * size];
            var white = new Color32(255, 255, 255, 255);
            var transparent = new Color32(0, 0, 0, 0);
            
            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    // 边框区域为白色，内部透明
                    bool isBorder = x < border || x >= size - border || 
                                    y < border || y >= size - border;
                    pixels[y * size + x] = isBorder ? white : transparent;
                }
            }
            
            texture.SetPixels32(pixels);
            texture.Apply();
            
            // 创建 Sprite（16 PPU，与 Tilemap 对齐）
            return Sprite.Create(texture, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), 16f);
        }
        
        
        /// <summary>
        /// 创建格子方框 Sprite（复刻 PlacementGridCell 的程序化格子）
        /// </summary>
        private Sprite CreateGridSprite()
        {
            int size = 32;
            int border = 2;
            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
            texture.filterMode = FilterMode.Point;
            var pixels = new Color32[size * size];
            var borderColor = new Color32(255, 255, 255, 204);  // alpha=0.8
            var fillColor = new Color32(255, 255, 255, 77);     // alpha=0.3
            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    bool isBorder = x < border || x >= size - border || y < border || y >= size - border;
                    pixels[y * size + x] = isBorder ? borderColor : fillColor;
                }
            }
            texture.SetPixels32(pixels);
            texture.Apply();
            return Sprite.Create(texture, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), 32f);
        }
        
        
        /// <summary>
        /// 从对象池获取或创建种子队列预览 SpriteRenderer
        /// </summary>
        private SpriteRenderer GetOrCreateSeedQueueRenderer()
        {
            if (seedQueuePool.Count > 0)
            {
                var sr = seedQueuePool[seedQueuePool.Count - 1];
                seedQueuePool.RemoveAt(seedQueuePool.Count - 1);
                return sr;
            }
            var go = new GameObject("SeedQueuePreview");
            go.transform.SetParent(transform, false);
            var renderer = go.AddComponent<SpriteRenderer>();
            renderer.sortingLayerName = "Layer 1";
            renderer.sortingOrder = 9998;
            return renderer;
        }
        
        /// <summary>
        /// 清除 GhostTilemap 上的所有预览 Tiles
        /// </summary>
        private void ClearGhostTilemap()
        {
            if (ghostTilemap == null) return;
            
            foreach (var pos in currentPreviewPositions)
            {
                ghostTilemap.SetTile(pos, null);
            }
            currentPreviewPositions.Clear();
        }

        /// <summary>
        /// 入队时调用：在指定位置显示队列锁定预览（CP-H5）
        /// </summary>
        public void AddQueuePreview(Vector3Int cellPos, int layerIndex, FarmActionType type, 
            int puddleVariant = -1, Dictionary<Vector3Int, TileBase> ghostTileData = null)
        {
            if (queuePreviewPositions.Contains(cellPos)) return;  // 防重复

            if (type == FarmActionType.PlantSeed)
            {
                // 种子队列预览：SpriteRenderer 对象池
                var renderer = GetOrCreateSeedQueueRenderer();
                renderer.transform.position = GetCellCenterWorld(layerIndex, cellPos);
                // 尝试获取当前种子的第一阶段 sprite
                renderer.color = new Color(1f, 1f, 1f, queuePreviewAlpha);
                renderer.enabled = true;
                activeSeedQueuePreviews.Add((cellPos, renderer));
            }
            else
            {
                // 耕地/浇水队列预览：queuePreviewTilemap
                TileBase tile = null;
                if (type == FarmActionType.Water)
                {
                    // 🔴 V3 模块L（CP-L1）：使用预分配的 puddleVariant 获取确定性 tile
                    if (puddleVariant >= 0)
                    {
                        var tiles = FarmVisualManager.Instance?.GetPuddleTiles();
                        if (tiles != null && puddleVariant < tiles.Length)
                            tile = tiles[puddleVariant];
                        else
                            tile = FarmVisualManager.Instance?.GetRandomPuddleTile(); // 兜底
                    }
                    else
                    {
                        tile = FarmVisualManager.Instance?.GetRandomPuddleTile(); // CP-L3：未分配时兜底随机
                    }
                }
                else if (type == FarmActionType.Till)
                {
                    // 🔴 补丁004 模块F（CP-F1）：优先使用 ghost 数据，兜底独立计算
                    Dictionary<Vector3Int, TileBase> tilesToPlace;
                    if (ghostTileData != null && ghostTileData.Count > 0)
                    {
                        tilesToPlace = ghostTileData;
                    }
                    else
                    {
                        // 兜底：独立计算（向后兼容 CP-F2）
                        tilesToPlace = new Dictionary<Vector3Int, TileBase>();
                        if (FarmlandBorderManager.Instance != null)
                        {
                            var previewTiles = FarmlandBorderManager.Instance.GetPreviewTiles(layerIndex, cellPos);
                            foreach (var kvp in previewTiles)
                            {
                                if (kvp.Value != null)
                                    tilesToPlace[kvp.Key] = kvp.Value;
                            }
                        }
                    }
                    
                    var tilePositions = new List<Vector3Int>();
                    foreach (var kvp in tilesToPlace)
                    {
                        if (kvp.Value != null && queuePreviewTilemap != null)
                        {
                            queuePreviewTilemap.SetTile(kvp.Key, kvp.Value);
                            queuePreviewTilemap.SetColor(kvp.Key, new Color(1f, 1f, 1f, queuePreviewAlpha));
                            tilePositions.Add(kvp.Key);
                        }
                    }
                    tillQueueTileGroups[cellPos] = tilePositions;
                }

                // 🔴 V3 模块K：Water 分支的 tile 放置移到上面的 if 块中已处理
                if (tile != null && queuePreviewTilemap != null && type == FarmActionType.Water)
                {
                    queuePreviewTilemap.SetTile(cellPos, tile);
                    queuePreviewTilemap.SetColor(cellPos, new Color(1f, 1f, 1f, queuePreviewAlpha));
                }
            }

            queuePreviewPositions.Add(cellPos);
        }

        /// <summary>
        /// 执行完成时调用：移除指定位置的队列预览（CP-H5）
        /// </summary>
        public void RemoveQueuePreview(Vector3Int cellPos)
        {
            if (!queuePreviewPositions.Contains(cellPos)) return;

            // 检查是否是种子队列预览
            int seedIndex = activeSeedQueuePreviews.FindIndex(x => x.cellPos == cellPos);
            if (seedIndex >= 0)
            {
                var entry = activeSeedQueuePreviews[seedIndex];
                entry.renderer.enabled = false;
                seedQueuePool.Add(entry.renderer);  // 回收到对象池
                activeSeedQueuePreviews.RemoveAt(seedIndex);
            }
            // 🔴 V3 模块K（CP-K2）：耕地队列从 tillQueueTileGroups 获取关联位置列表
            else if (tillQueueTileGroups.TryGetValue(cellPos, out var tilePositions))
            {
                if (queuePreviewTilemap != null)
                {
                    foreach (var pos in tilePositions)
                    {
                        queuePreviewTilemap.SetTile(pos, null);
                    }
                }
                tillQueueTileGroups.Remove(cellPos);
            }
            else if (queuePreviewTilemap != null)
            {
                // 浇水等：单点清除
                queuePreviewTilemap.SetTile(cellPos, null);
            }

            queuePreviewPositions.Remove(cellPos);
        }

        /// <summary>
        /// 清空所有队列预览（WASD 中断 / 切换工具 / ESC）（CP-H5）
        /// </summary>
        public void ClearAllQueuePreviews()
        {
            // 🔴 补丁004 模块E（CP-E1/E2）：清除耕地队列的所有 tile（中心块 + 边界），跳过执行预览
            if (queuePreviewTilemap != null)
            {
                foreach (var kvp in tillQueueTileGroups)
                {
                    if (executingTileGroups.ContainsKey(kvp.Key)) continue;  // CP-E3：跳过执行预览
                    foreach (var pos in kvp.Value)
                        queuePreviewTilemap.SetTile(pos, null);
                }
                
                // 清除浇水等单点队列预览，跳过执行预览
                foreach (var pos in queuePreviewPositions)
                {
                    if (executingWaterPositions.Contains(pos)) continue;  // CP-E3：跳过执行预览
                    if (tillQueueTileGroups.ContainsKey(pos)) continue;  // 已在上面处理
                    queuePreviewTilemap.SetTile(pos, null);
                }
            }

            // 回收种子队列预览（跳过执行中的）
            for (int i = activeSeedQueuePreviews.Count - 1; i >= 0; i--)
            {
                var entry = activeSeedQueuePreviews[i];
                if (executingSeedPreviews.Exists(x => x.cellPos == entry.cellPos)) continue;
                entry.renderer.enabled = false;
                seedQueuePool.Add(entry.renderer);
                activeSeedQueuePreviews.RemoveAt(i);
            }
            activeSeedQueuePreviews.Clear();

            queuePreviewPositions.Clear();
            
            // 🔴 V3 模块K（CP-K3）：清空耕地 tile 组追踪（不清 executing* 数据）
            tillQueueTileGroups.Clear();
        }
        
        /// <summary>
        /// 🔴 补丁004 模块D（CP-D1）：将队列预览提升为执行预览。
        /// ProcessNextAction 出队时调用。tile 保留在 queuePreviewTilemap 上，只转移追踪数据。
        /// </summary>
        public void PromoteToExecutingPreview(Vector3Int cellPos)
        {
            // 耕地：从 tillQueueTileGroups 转移到 executingTileGroups
            if (tillQueueTileGroups.TryGetValue(cellPos, out var tilePositions))
            {
                executingTileGroups[cellPos] = tilePositions;
                tillQueueTileGroups.Remove(cellPos);
            }
            // 浇水：从 queuePreviewPositions 转移到 executingWaterPositions
            else if (queuePreviewPositions.Contains(cellPos) && !activeSeedQueuePreviews.Exists(x => x.cellPos == cellPos))
            {
                executingWaterPositions.Add(cellPos);
            }
            // 种子：从 activeSeedQueuePreviews 转移到 executingSeedPreviews
            else
            {
                int idx = activeSeedQueuePreviews.FindIndex(x => x.cellPos == cellPos);
                if (idx >= 0)
                {
                    executingSeedPreviews.Add(activeSeedQueuePreviews[idx]);
                    activeSeedQueuePreviews.RemoveAt(idx);
                }
            }
            
            // 从队列追踪中移除（但 tile 保留在 tilemap 上）
            queuePreviewPositions.Remove(cellPos);
        }
        
        /// <summary>
        /// 🔴 补丁004 模块D（CP-D2）：清除执行预览。
        /// 动画完成后调用，此时 tile 已落地，视觉无缝。
        /// </summary>
        public void RemoveExecutingPreview(Vector3Int cellPos)
        {
            // 耕地：清除关联的所有 tile
            if (executingTileGroups.TryGetValue(cellPos, out var tilePositions))
            {
                if (queuePreviewTilemap != null)
                {
                    foreach (var pos in tilePositions)
                        queuePreviewTilemap.SetTile(pos, null);
                }
                executingTileGroups.Remove(cellPos);
                return;
            }
            
            // 浇水：清除单点
            if (executingWaterPositions.Contains(cellPos))
            {
                queuePreviewTilemap?.SetTile(cellPos, null);
                executingWaterPositions.Remove(cellPos);
                return;
            }
            
            // 种子：回收 SpriteRenderer
            int idx = executingSeedPreviews.FindIndex(x => x.cellPos == cellPos);
            if (idx >= 0)
            {
                var entry = executingSeedPreviews[idx];
                entry.renderer.enabled = false;
                seedQueuePool.Add(entry.renderer);
                executingSeedPreviews.RemoveAt(idx);
            }
        }

        
        /// <summary>
        /// 更新光标位置和颜色
        /// </summary>
        private void UpdateCursor(int layerIndex, Vector3Int cellPos)
        {
            if (cursorRenderer == null) return;
            
            // 获取格子中心世界坐标
            var tilemaps = FarmTileManager.Instance?.GetLayerTilemaps(layerIndex);
            Vector3 worldPos;
            
            if (tilemaps != null)
            {
                worldPos = tilemaps.GetCellCenterWorld(cellPos);
            }
            else
            {
                // 回退：使用 PlacementGridCalculator
                worldPos = PlacementGridCalculator.GetCellCenter(new Vector3(cellPos.x, cellPos.y, 0));
            }
            
            cursorRenderer.transform.position = worldPos;
            
            // 设置颜色
            Color color;
            if (!isHoeMode && currentState == FarmPreviewState.Valid)
            {
                // 水壶有效 = 蓝色
                color = wateringColor;
            }
            else if (currentState == FarmPreviewState.Valid)
            {
                // 锄头有效 = 绿色
                color = validColor;
            }
            else
            {
                // 无效 = 红色
                color = invalidColor;
            }
            
            cursorRenderer.color = color;
        }
        
        /// <summary>
        /// 🔥 新增：更新种子模式的光标
        /// </summary>
        private void UpdateCursorForSeed(Vector3 worldPos, bool isValid)
        {
            if (cursorRenderer == null) return;
            
            cursorRenderer.transform.position = worldPos;
            cursorRenderer.color = isValid ? seedValidColor : seedInvalidColor;
        }
        
        /// <summary>
        /// 🔥 新增：更新 Sorting Layer（跟随玩家楼层）
        /// </summary>
        private void UpdateSortingLayer(Transform playerTransform)
        {
            if (playerTransform == null) return;
            
            string playerSortingLayer = PlacementLayerDetector.GetPlayerSortingLayer(playerTransform);
            
            // 只在 Layer 变化时更新
            if (playerSortingLayer != currentSortingLayer)
            {
                currentSortingLayer = playerSortingLayer;
                
                // 更新 GhostTilemap 的 Sorting Layer
                if (ghostTilemapRenderer != null)
                {
                    ghostTilemapRenderer.sortingLayerName = currentSortingLayer;
                }
                
                // 更新 CursorRenderer 的 Sorting Layer
                if (cursorRenderer != null)
                {
                    cursorRenderer.sortingLayerName = currentSortingLayer;
                }
                
                if (showDebugInfo)
                {
                    Debug.Log($"[FarmToolPreview] Sorting Layer 更新为: {currentSortingLayer}");
                }
            }
        }
        
        /// <summary>
        /// 🔥 新增：获取玩家中心位置
        /// </summary>
        private Vector2 GetPlayerCenter(Transform playerTransform)
        {
            if (playerTransform == null) return Vector2.zero;
            
            var collider = playerTransform.GetComponent<Collider2D>();
            return collider != null ? (Vector2)collider.bounds.center : (Vector2)playerTransform.position;
        }
        
        /// <summary>
        /// 🔥 新增：获取格子中心世界坐标
        /// </summary>
        private Vector3 GetCellCenterWorld(int layerIndex, Vector3Int cellPos)
        {
            var tilemaps = FarmTileManager.Instance?.GetLayerTilemaps(layerIndex);
            if (tilemaps != null)
            {
                return tilemaps.GetCellCenterWorld(cellPos);
            }
            
            // 回退：使用 PlacementGridCalculator
            return PlacementGridCalculator.GetCellCenter(new Vector3(cellPos.x + 0.5f, cellPos.y + 0.5f, 0));
        }
        
        /// <summary>
        /// 🔥 新增：检查是否在使用距离内
        /// </summary>
        private bool IsWithinReach(Transform playerTransform, Vector3 targetPos, float reach)
        {
            Vector2 playerCenter = GetPlayerCenter(playerTransform);
            float distance = Vector2.Distance(playerCenter, targetPos);
            return distance <= reach;
        }
        
        #endregion
    }
}
